pipeline {
    agent {
        docker {
            image 'maven:3.8.5-openjdk-11-slim'
            args '-v /root/.m2:/root/.m2'
        }
    }
   stages {
        stage('Build') {
            steps {
                sh 'mvn -X -DskipTests clean package'
            }
        }
    }
}
