pipeline {
    agent {
        docker {
            image 'maven:3.8.5-openjdk-17-slim'            
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                sh 'mvn surefire-report:report'
            }
            post {
                always {
                    junit 'target/site/surefire-reports.html/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Does Not Yet Exist'
            }
        }
    }
}
