pipeline {
    agent {
        docker {
            image 'maven:3.8.1-eclipse-temurin-11-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
   stages {
        stage('Build') {
            steps {
                sh 'mvn -X -DskipTests clean package'
            }
        }
    }
}
